#!/bin/bash

# Install all scriptlets, excluding this one,
# from the current directory to /usr/local/bin.

DESTINATION_PATH="/usr/local/bin"

# Verify that the destination path exists.
if [ ! -d "$DESTINATION_PATH" ]; then
  echo "Error: The specified destination '$DESTINATION_PATH' does not exist"
  exit 1
fi

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
SCRIPT_NAME=$(basename "$SCRIPT_PATH")

# Verify running as root or with sudo for copying to /usr/local/bin.
if [ "$(id -u)" -ne 0 ]; then
  echo "Error: Please run as root or use sudo to install to '$DESTINATION_PATH'."
  exit 1
fi

for file in *; do
  # Check if the file is an executable.
  if [[ -x "$file" && -f "$file" ]]; then
    # Copy all files except this one.
    if [[ "$file" != "$SCRIPT_NAME" ]]; then
      echo "Installing $file to '$DESTINATION_PATH'"
      if ! cp "$file" "$DESTINATION_PATH"; then
        echo "Error: Failed to copy $file to $DESTINATION_PATH."
        exit 1
      fi
    fi
  fi
done

# Check if at least one file has been successfully copied.
if [ "$(ls -1 $DESTINATION_PATH | wc -l)" -eq 0 ]; then
  echo "Installation unsuccessful: No files were copied to '$DESTINATION_PATH'."
  exit 1
else
  echo "Installation successful."
fi

echo "Done."
