#!/bin/bash

# Check if an argument was provided
if [ $# -eq 0 ]; then
  echo "Usage: status <INSTANCE_NAME>"
  exit 1
fi

INSTANCE_NAME=$1

# Convert INSTANCE_NAME to uppercase using tr
UPPERCASE_INSTANCE_NAME=$(echo "$INSTANCE_NAME" | tr '[:lower:]' '[:upper:]')

ENV_VAR_NAME="INSTANCE_ID_$UPPERCASE_INSTANCE_NAME"

INSTANCE_ID=${!ENV_VAR_NAME}

aws ec2 describe-instances \
    --instance-ids $INSTANCE_ID \
    --query 'Reservations[].Instances[].State.Name' \
    --output text

